name: multi_finger_gesture_detector
description: "Multi Finger Gesture Detector is custom widget for detecting multiple fingers gestures, Its use GestureDetector Widget to detect gestures."
version: 1.0.1
homepage: https://github.com/KodeSaiRatnakar
repository: https://github.com/KodeSaiRatnakar/multi_finger_gesture_detector
issue_tracker: https://github.com/KodeSaiRatnakar/multi_finger_gesture_detector/issues

# platforms:
#   android:
#   ios:
#   macos:
#   web:
#   windows:

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
